### ISSUE TITLE
Classic Mode Gamemodes in Platformer

### ISSUE THREAD

**Issue by Aktimoose** [user95401/Platformered-Menu-Game#1]
The ship, swing, and wave all look weird. It would make sense to replace the ship with the jetpack, and eliminate swing and wave spawns entirely. Swing isn't that bad but the wave has a ton of issues (the entire wave trail can move up at times and wave in platformer just looks messed up)
Could probably make this an option in settings?

**Comment by lil2kki** [comment]
ok

**Comment by lil2kki** [comment]
yea
![image](https://github.com/user-attachments/assets/5e07b381-6fc9-4720-b317-4e654b2effa5)
![image](https://github.com/user-attachments/assets/9e557291-8183-4f20-84c1-4bcaa603ad8f)

**Comment by lil2kki** [comment]
https://github.com/user95401/Platformered-Menu-Game/releases/tag/v1.1.0
